Algoritmo "CRESCENTE E DECRESCENTE"

Var
   N1, N2: INTEIRO


Inicio
n1<-1
n2<-2
   ESCREVAl ("========== CRESCENTE/DECRESCENTE ==========")
   enquanto n1<>n2 faca
            escreval ("Digite dois números: ")
            leia (n1)
            leia (n2)
            se n1>n2 entao
               escreval ("DECRESCENTE")
               senao
                    escreval ("CRESCENTE")
            fimSe
   
   fimEnquanto
   



Fimalgoritmo